### ISSUE TITLE
exit with error code 2 on parse failure

### ISSUE THREAD

**Issue by ahl** [spullara/cli-parser#14]
`parseOrExit()` exits with code 1 on failure; I'd suggest that 2 may be more in keeping with the UNIX tradition, but you could also consider POSIX (/usr/include/sysexits.h `EX_USAGE = 64`).

**Comment by spullara** [comment]
https://github.com/spullara/cli-parser/commit/257e7c208f4f9d99df127153aba10c91b3e03adc
